### ISSUE TITLE
L'url "bpetetot.fr" ne fonctionne pas

### ISSUE THREAD

**Issue by jlandure** [GDG-Nantes/devfest2017#100]
Voilà l'url qui ne marche pas...
https://tweetledee.petetot.fr/favoritesjson.php?c=10&cache_interval=8000

sur notre site en prod... A voir si c'est viable sur le long terme cette url ou si on l'héberge pas quelque part ✌️

**Comment by bpetetot** [comment]
ça refonctionne, en effet je ne peux pas garantir un SLA de 100% dessus, mais je ferai très attention...

Mais si vous voulez l'héberger autre part c'est docker-composé ;)

```
version: '2'
services:
  client:
    build:
      context: .
      dockerfile: config/Dockerfile
    container_name: tweetledee
    ports:
      - "9990:80"
    volumes:
      - ./tweetledee:/var/www/html
      - ./config/apache2.conf:/etc/apache2/apache2.conf
      - ./config/apache-site.conf:/etc/apache2/sites-enabled/000-default.conf
```
